// Master student records used by the dashboard.
// Each record keeps the original id, name, section and scores from the
// web app and adds the fields. an admin needs day-to-day: contact
// email, enrollment "active" flag and enrollment date.
//
// `avatarUrl` is optional: when set to an http(s) image URL the avatar
// system shows that photo (cropped/centered); when empty the UI shows a
// polished deterministic initials avatar — never a random photo.
export const students = [
    {
        id: 101,
        name: "Ana Santos",
        email: "ana.santos@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-15",
        scores: [90, 85, 88],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921124.png",
    },
    {
        id: 102,
        name: "Ben Cruz",
        email: "ben.cruz@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-15",
        scores: [70, 72, 74],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/16683/16683419.png",
    },
    {
        id: 103,
        name: "Carlo Reyes",
        email: "carlo.reyes@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-20",
        scores: [95, 90, 92],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219970.png",
    },
    {
        id: 104,
        name: "Dina Garcia",
        email: "dina.garcia@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-20",
        scores: [78, 82, 80],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140060.png",
    },
    {
        id: 105,
        name: "Eric Mendoza",
        email: "eric.mendoza@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-18",
        scores: [65, 68, 70],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140077.png",
    },
    {
        id: 106,
        name: "Faith Lim",
        email: "faith.lim@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-14",
        scores: [88, 91, 86],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140047.png",
    },
    {
        id: 107,
        name: "Grace Tan",
        email: "grace.tan@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-14",
        scores: [82, 79, 85],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/1154/1154448.png",
    },
    {
        id: 108,
        name: "Henry Yu",
        email: "henry.yu@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-16",
        scores: [55, 75, 58],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4202/4202831.png",
    },
    {
        id: 109,
        name: "Ira Solis",
        email: "ira.solis@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-19",
        scores: [92, 88, 90],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/13482/13482227.png",
    },
    {
        id: 110,
        name: "Jay Perez",
        email: "jay.perez@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-15",
        scores: [84, 81, 87],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135825.png",
    },
    {
        id: 111,
        name: "Kim Aquino",
        email: "kim.aquino@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-16",
        scores: [91, 89, 94],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135789.png",
    },
    {
        id: 112,
        name: "Leo Ramos",
        email: "leo.ramos@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-17",
        scores: [73, 76, 71],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135768.png",
    },
    {
        id: 113,
        name: "Mia Torres",
        email: "mia.torres@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-18",
        scores: [96, 93, 95],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135801.png",
    },
    {
        id: 114,
        name: "Nina Diaz",
        email: "nina.diaz@school.edu",
        section: "B",
        active: false,
        enrolled: "2026-08-19",
        scores: [68, 70, 66],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135926.png",
    },
    {
        id: 115,
        name: "Omar Villanueva",
        email: "omar.villanueva@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-14",
        scores: [80, 83, 79],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135957.png",
    },
    {
        id: 116,
        name: "Paula Navarro",
        email: "paula.navarro@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-20",
        scores: [87, 85, 89],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135843.png",
    },
    {
        id: 117,
        name: "Quinn Castillo",
        email: "quinn.castillo@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-21",
        scores: [77, 74, 78],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135885.png",
    },
    {
        id: 118,
        name: "Rosa Flores",
        email: "rosa.flores@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-15",
        scores: [93, 90, 91],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135905.png",
    },
    {
        id: 119,
        name: "Sam Ortega",
        email: "sam.ortega@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-16",
        scores: [62, 65, 60],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/3135/3135875.png",
    },
    {
        id: 120,
        name: "Tina Salazar",
        email: "tina.salazar@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-17",
        scores: [89, 92, 90],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140051.png",
    },
    {
        id: 121,
        name: "Ulysses Bautista",
        email: "ulysses.bautista@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-18",
        scores: [71, 69, 74],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140037.png",
    },
    {
        id: 122,
        name: "Vera Ocampo",
        email: "vera.ocampo@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-19",
        scores: [85, 88, 84],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140061.png",
    },
    {
        id: 123,
        name: "Will Delgado",
        email: "will.delgado@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-20",
        scores: [76, 79, 75],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140027.png",
    },
    {
        id: 124,
        name: "Xena Marquez",
        email: "xena.marquez@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-14",
        scores: [94, 96, 93],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140057.png",
    },
    {
        id: 125,
        name: "Yuri Padilla",
        email: "yuri.padilla@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-21",
        scores: [67, 64, 69],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140048.png",
    },
    {
        id: 126,
        name: "Zara Velasco",
        email: "zara.velasco@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-15",
        scores: [90, 93, 89],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4140/4140067.png",
    },
    {
        id: 127,
        name: "Aaron Dizon",
        email: "aaron.dizon@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-16",
        scores: [58, 61, 57],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/924/924874.png",
    },
    {
        id: 128,
        name: "Bella Corpuz",
        email: "bella.corpuz@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-17",
        scores: [83, 86, 82],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921097.png",
    },
    {
        id: 129,
        name: "Chris Aguilar",
        email: "chris.aguilar@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-18",
        scores: [79, 77, 81],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/924/924915.png",
    },
    {
        id: 130,
        name: "Dana Villamor",
        email: "dana.villamor@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-19",
        scores: [92, 94, 90],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921071.png",
    },
    {
        id: 131,
        name: "Evan Cortez",
        email: "evan.cortez@school.edu",
        section: "A",
        active: false,
        enrolled: "2026-08-20",
        scores: [70, 73, 68],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/924/924867.png",
    },
    {
        id: 132,
        name: "Fiona Santiago",
        email: "fiona.santiago@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-14",
        scores: [86, 84, 88],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921143.png",
    },
    {
        id: 133,
        name: "Gabe Morales",
        email: "gabe.morales@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-15",
        scores: [75, 72, 78],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/924/924884.png",
    },
    {
        id: 134,
        name: "Hana Domingo",
        email: "hana.domingo@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-16",
        scores: [97, 95, 98],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921059.png",
    },
    {
        id: 135,
        name: "Ivan Fernandez",
        email: "ivan.fernandez@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-17",
        scores: [66, 69, 63],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/924/924892.png",
    },
    {
        id: 136,
        name: "Jessa Lopez",
        email: "jessa.lopez@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-18",
        scores: [88, 86, 91],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921089.png",
    },
    {
        id: 137,
        name: "Karl Gutierrez",
        email: "karl.gutierrez@school.edu",
        section: "A",
        active: false,
        enrolled: "2026-08-19",
        scores: [59, 62, 56],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/924/924908.png",
    },
    {
        id: 138,
        name: "Lena Pascual",
        email: "lena.pascual@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-20",
        scores: [81, 84, 80],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/921/921116.png",
    },
    {
        id: 139,
        name: "Marco Rivera",
        email: "marco.rivera@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-21",
        scores: [74, 71, 76],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219969.png",
    },
    {
        id: 140,
        name: "Nadia Castillo",
        email: "nadia.castillo@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-14",
        scores: [93, 91, 95],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219986.png",
    },
    {
        id: 141,
        name: "Owen Sy",
        email: "owen.sy@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-15",
        scores: [69, 72, 67],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219983.png",
    },
    {
        id: 142,
        name: "Pamela Uy",
        email: "pamela.uy@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-16",
        scores: [84, 87, 82],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219989.png",
    },
    {
        id: 143,
        name: "Rico Jimenez",
        email: "rico.jimenez@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-17",
        scores: [78, 80, 76],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219964.png",
    },
    {
        id: 144,
        name: "Sofia Gonzales",
        email: "sofia.gonzales@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-18",
        scores: [95, 92, 97],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/219/219971.png",
    },
    {
        id: 145,
        name: "Tristan Co",
        email: "tristan.co@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-19",
        scores: [63, 66, 61],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4202/4202842.png",
    },
    {
        id: 146,
        name: "Uma Reyes",
        email: "uma.reyes@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-20",
        scores: [89, 87, 92],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4202/4202840.png",
    },
    {
        id: 147,
        name: "Victor Cruz",
        email: "victor.cruz@school.edu",
        section: "B",
        active: false,
        enrolled: "2026-08-21",
        scores: [72, 75, 70],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4202/4202839.png",
    },
    {
        id: 148,
        name: "Wendy Chua",
        email: "wendy.chua@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-14",
        scores: [91, 88, 94],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4202/4202835.png",
    },
    {
        id: 149,
        name: "Xander Lim",
        email: "xander.lim@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-15",
        scores: [82, 85, 80],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/4202/4202836.png",
    },
    {
        id: 150,
        name: "Yara Santos",
        email: "yara.santos@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-16",
        scores: [87, 90, 85],
        avatarUrl: "https://cdn-icons-png.flaticon.com/128/1154/1154709.png",
    },
];
