// Master student records used by the dashboard.
// Each record keeps the original id, name, section and scores from the
// web app and adds the fields. an admin needs day-to-day: contact
// email, enrollment "active" flag and enrollment date.
export const students = [
    {
        id: 101,
        name: "Ana Santos",
        email: "ana.santos@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-15",
        scores: [90, 85, 88],
    },
    {
        id: 102,
        name: "Ben Cruz",
        email: "ben.cruz@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-15",
        scores: [70, 72, 74],
    },
    {
        id: 103,
        name: "Carlo Reyes",
        email: "carlo.reyes@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-20",
        scores: [95, 90, 92],
    },
    {
        id: 104,
        name: "Dina Garcia",
        email: "dina.garcia@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-20",
        scores: [78, 82, 80],
    },
    {
        id: 105,
        name: "Eric Mendoza",
        email: "eric.mendoza@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-18",
        scores: [65, 68, 70],
    },
    {
        id: 106,
        name: "Faith Lim",
        email: "faith.lim@school.edu",
        section: "C",
        active: true,
        enrolled: "2026-08-14",
        scores: [88, 91, 86],
    },
    {
        id: 107,
        name: "Grace Tan",
        email: "grace.tan@school.edu",
        section: "A",
        active: true,
        enrolled: "2026-08-14",
        scores: [82, 79, 85],
    },
    {
        id: 108,
        name: "Henry Yu",
        email: "henry.yu@school.edu",
        section: "B",
        active: true,
        enrolled: "2026-08-16",
        scores: [55, 75, 58],
    },
    {
        id: 109,
        name: "Ira Solis",
        email: "ira.solis@school.edu",
        section: "C",
        active: false,
        enrolled: "2026-08-19",
        scores: [92, 88, 90],
    },
];
